# ===================================================================
# Default GitHub Scheduler Setup
# ===================================================================

name: Scheduled Jobs

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
# github scheduler not supported seconds cron feature
on:
  schedule:
    # https://crontab.guru
    - cron: '0 */1 * * *'
    
# Job Tasks
jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      # Echo
      - name: echo job
        run: echo "Welcome to 극락코딩"

      # Start Job
      - name: start Job
        run: date

      # Checkout
      - name: repository checkout
        uses: actions/checkout@v2
        with:
          repository: DongGeon0908/travel-to-the-past
          token: ${{ secrets.GOOFY_GITHUB_TOKEN }}
          path: github-action

      # Subtract 1 day from the last recorded date
      - name: Subtract 1 day from recorded date
        run: |
          cd github-action
          
          # 파일에 기록된 마지막 날짜를 읽고 파싱
          if [ -f past-history.txt ]; then
            last_date=$(tail -n 1 past-history.txt)
          else
            last_date=$(date '+%a %b %d %T %Z %Y') # 파일이 없으면 현재 시간으로 초기화
          fi
          
          # 날짜에서 1일 빼기
          new_date=$(date -d "$last_date -1 day" '+%a %b %d %T %Z %Y')
          
          # 새로운 날짜를 파일에 기록
          echo $new_date >> past-history.txt
          echo "- $new_date" >> README.md
          
          # git 설정
          git config --global user.email "wrjssmjdhappy@gmail.com"
          git config --global user.name "극락코딩"
          
          # GIT_COMMITTER_DATE와 GIT_AUTHOR_DATE를 설정하여 커밋 날짜 변경
          GIT_COMMITTER_DATE="$new_date" GIT_AUTHOR_DATE="$new_date" git add .
          GIT_COMMITTER_DATE="$new_date" GIT_AUTHOR_DATE="$new_date" git commit -m "과거로 시간 여행 $new_date (by 극락코딩)"
          git push origin main


      # End Job
      - name: end Job
        run: date
